# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome')),
                ('telefone', models.CharField(blank=True, max_length=50)),
                ('localDeOrigem', models.CharField(blank=True, max_length=255, verbose_name='Local de Origem')),
                ('data', models.DateTimeField(blank=True, null=True, verbose_name='Data')),
                ('horario', models.DateTimeField(auto_now_add=True)),
                ('localDeDestino', models.CharField(blank=True, max_length=255, verbose_name='Local de Destino')),
                ('cep', models.CharField(max_length=8, unique=True, verbose_name='CEP')),
                ('logadouro', models.CharField(max_length=255)),
                ('complemento', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('localidade', models.CharField(max_length=255)),
                ('uf', models.CharField(max_length=2)),
                ('descricao', models.TextField(max_length=500, verbose_name='Descri\xe7\xe3o')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
            },
        ),
    ]
